apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: fion-auth
    app.kubernetes.io/name: fion-auth
  name: fion-auth
  namespace: dev
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: fion-auth
    app.kubernetes.io/name: fion-auth
  sessionAffinity: None
  type: ClusterIP
