name: Prod - Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::891377357860:role/github-eks-role
          aws-region: eu-central-1

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig
        run: aws eks --region eu-central-1 update-kubeconfig --name fion-prod

      - name: Deploy with yaml
        run: |
          sed -i 's/commit-sha-latest/${{ github.event.inputs.image_tag }}/g' ./deploy/prod/deployment.yaml
          kubectl apply -f ./deploy/prod/deployment.yaml
          kubectl apply -f ./deploy/prod/ingress.yaml
          kubectl apply -f ./deploy/prod/serviceaccount.yaml
          kubectl apply -f ./deploy/prod/service.yaml
